"""doc_named_width_tables

Revision ID: 3d27b7c3dd42
Revises: afc64362c147
Create Date: 2026-06-04 05:58:22.659845
"""
from alembic import op
import sqlalchemy as sa


revision = '3d27b7c3dd42'
down_revision = 'afc64362c147'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatops_commands',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('command', sa.String(), nullable=False),
    sa.Column('at', sa.String(), nullable=False),
    sa.Column('document', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chatops_commands_at'), 'chatops_commands', ['at'], unique=False)
    op.create_index(op.f('ix_chatops_commands_command'), 'chatops_commands', ['command'], unique=False)
    op.create_index(op.f('ix_chatops_commands_user_id'), 'chatops_commands', ['user_id'], unique=False)
    op.create_table('cost_metrics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('service_id', sa.String(), nullable=False),
    sa.Column('captured_at', sa.String(), nullable=False),
    sa.Column('document', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cost_metrics_captured_at'), 'cost_metrics', ['captured_at'], unique=False)
    op.create_index(op.f('ix_cost_metrics_service_id'), 'cost_metrics', ['service_id'], unique=False)
    op.create_table('fleet_venues',
    sa.Column('venue_id', sa.String(), nullable=False),
    sa.Column('document', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('venue_id')
    )
    op.create_table('on_call_schedules',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tier', sa.String(), nullable=False),
    sa.Column('document', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_on_call_schedules_tier'), 'on_call_schedules', ['tier'], unique=False)
    op.create_table('slo_catalog',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('service_id', sa.String(), nullable=False),
    sa.Column('document', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_slo_catalog_service_id'), 'slo_catalog', ['service_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_slo_catalog_service_id'), table_name='slo_catalog')
    op.drop_table('slo_catalog')
    op.drop_index(op.f('ix_on_call_schedules_tier'), table_name='on_call_schedules')
    op.drop_table('on_call_schedules')
    op.drop_table('fleet_venues')
    op.drop_index(op.f('ix_cost_metrics_service_id'), table_name='cost_metrics')
    op.drop_index(op.f('ix_cost_metrics_captured_at'), table_name='cost_metrics')
    op.drop_table('cost_metrics')
    op.drop_index(op.f('ix_chatops_commands_user_id'), table_name='chatops_commands')
    op.drop_index(op.f('ix_chatops_commands_command'), table_name='chatops_commands')
    op.drop_index(op.f('ix_chatops_commands_at'), table_name='chatops_commands')
    op.drop_table('chatops_commands')
    # ### end Alembic commands ###
