"""width_module_tables

Revision ID: afc64362c147
Revises: 00797b4ba612
Create Date: 2026-06-03 22:37:33.798164
"""
from alembic import op
import sqlalchemy as sa


revision = 'afc64362c147'
down_revision = '00797b4ba612'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('change_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('service_id', sa.String(), nullable=False),
    sa.Column('change_type', sa.String(), nullable=False),
    sa.Column('at', sa.String(), nullable=False),
    sa.Column('document', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_change_events_at'), 'change_events', ['at'], unique=False)
    op.create_index(op.f('ix_change_events_change_type'), 'change_events', ['change_type'], unique=False)
    op.create_index(op.f('ix_change_events_service_id'), 'change_events', ['service_id'], unique=False)
    op.create_table('davis_feedback',
    sa.Column('problem_id', sa.String(), nullable=False),
    sa.Column('rank', sa.Float(), nullable=False),
    sa.Column('document', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('problem_id')
    )
    op.create_index(op.f('ix_davis_feedback_rank'), 'davis_feedback', ['rank'], unique=False)
    op.create_table('postmortems',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('incident_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('document', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_postmortems_created_at'), 'postmortems', ['created_at'], unique=False)
    op.create_index(op.f('ix_postmortems_incident_id'), 'postmortems', ['incident_id'], unique=False)
    op.create_index(op.f('ix_postmortems_status'), 'postmortems', ['status'], unique=False)
    op.create_table('runbook_executions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('runbook_id', sa.String(), nullable=False),
    sa.Column('started_at', sa.String(), nullable=False),
    sa.Column('document', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runbook_executions_runbook_id'), 'runbook_executions', ['runbook_id'], unique=False)
    op.create_index(op.f('ix_runbook_executions_started_at'), 'runbook_executions', ['started_at'], unique=False)
    op.create_table('runbooks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('document', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runbooks_category'), 'runbooks', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_runbooks_category'), table_name='runbooks')
    op.drop_table('runbooks')
    op.drop_index(op.f('ix_runbook_executions_started_at'), table_name='runbook_executions')
    op.drop_index(op.f('ix_runbook_executions_runbook_id'), table_name='runbook_executions')
    op.drop_table('runbook_executions')
    op.drop_index(op.f('ix_postmortems_status'), table_name='postmortems')
    op.drop_index(op.f('ix_postmortems_incident_id'), table_name='postmortems')
    op.drop_index(op.f('ix_postmortems_created_at'), table_name='postmortems')
    op.drop_table('postmortems')
    op.drop_index(op.f('ix_davis_feedback_rank'), table_name='davis_feedback')
    op.drop_table('davis_feedback')
    op.drop_index(op.f('ix_change_events_service_id'), table_name='change_events')
    op.drop_index(op.f('ix_change_events_change_type'), table_name='change_events')
    op.drop_index(op.f('ix_change_events_at'), table_name='change_events')
    op.drop_table('change_events')
    # ### end Alembic commands ###
